<?php

namespace Database\Seeders;

use App\Models\Government;
use App\Models\GovernmentShippingPrice;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GovernmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $governments = [
            // دولة الجزائر
            ['id' => 1, 'country_id' => 1, 'name' => ['en' => 'Adrar', 'ar' => 'أدرار']],
            ['id' => 2, 'country_id' => 1, 'name' => ['en' => 'Chlef', 'ar' => 'الشلف']],
            ['id' => 3, 'country_id' => 1, 'name' => ['en' => 'Laghouat', 'ar' => 'الأغواط']],
            ['id' => 4, 'country_id' => 1, 'name' => ['en' => 'Oum El Bouaghi', 'ar' => 'أم البواقي']],
            ['id' => 5, 'country_id' => 1, 'name' => ['en' => 'Batna', 'ar' => 'باتنة']],
            ['id' => 6, 'country_id' => 1, 'name' => ['en' => 'Béjaïa', 'ar' => 'بجاية']],
            ['id' => 7, 'country_id' => 1, 'name' => ['en' => 'Biskra', 'ar' => 'بسكرة']],
            ['id' => 8, 'country_id' => 1, 'name' => ['en' => 'Béchar', 'ar' => 'بشار']],
            ['id' => 9, 'country_id' => 1, 'name' => ['en' => 'Blida', 'ar' => 'البليدة']],
            ['id' => 10, 'country_id' => 1, 'name' => ['en' => 'Bouïra', 'ar' => 'البويرة']],
            ['id' => 11, 'country_id' => 1, 'name' => ['en' => 'Tamanrasset', 'ar' => 'تمنراست']],
            ['id' => 12, 'country_id' => 1, 'name' => ['en' => 'Tébessa', 'ar' => 'تبسة']],
            ['id' => 13, 'country_id' => 1, 'name' => ['en' => 'Tlemcen', 'ar' => 'تلمسان']],
            ['id' => 14, 'country_id' => 1, 'name' => ['en' => 'Tiaret', 'ar' => 'تيارت']],
            ['id' => 15, 'country_id' => 1, 'name' => ['en' => 'Tizi Ouzou', 'ar' => 'تيزي وزو']],
            ['id' => 16, 'country_id' => 1, 'name' => ['en' => 'Algiers', 'ar' => 'الجزائر']],
            ['id' => 17, 'country_id' => 1, 'name' => ['en' => 'Djelfa', 'ar' => 'الجلفة']],
            ['id' => 18, 'country_id' => 1, 'name' => ['en' => 'Jijel', 'ar' => 'جيجل']],
            ['id' => 19, 'country_id' => 1, 'name' => ['en' => 'Sétif', 'ar' => 'سطيف']],
            ['id' => 20, 'country_id' => 1, 'name' => ['en' => 'Saïda', 'ar' => 'سعيدة']],
            ['id' => 21, 'country_id' => 1, 'name' => ['en' => 'Skikda', 'ar' => 'سكيكدة']],
            ['id' => 22, 'country_id' => 1, 'name' => ['en' => 'Sidi Bel Abbès', 'ar' => 'سيدي بلعباس']],
            ['id' => 23, 'country_id' => 1, 'name' => ['en' => 'Annaba', 'ar' => 'عنابة']],
            ['id' => 24, 'country_id' => 1, 'name' => ['en' => 'Guelma', 'ar' => 'قالمة']],
            ['id' => 25, 'country_id' => 1, 'name' => ['en' => 'Constantine', 'ar' => 'قسنطينة']],
            ['id' => 26, 'country_id' => 1, 'name' => ['en' => 'Médéa', 'ar' => 'المدية']],
            ['id' => 27, 'country_id' => 1, 'name' => ['en' => 'Mostaganem', 'ar' => 'مستغانم']],
            ['id' => 28, 'country_id' => 1, 'name' => ['en' => 'M’Sila', 'ar' => 'المسيلة']],
            ['id' => 29, 'country_id' => 1, 'name' => ['en' => 'Mascara', 'ar' => 'معسكر']],
            ['id' => 30, 'country_id' => 1, 'name' => ['en' => 'Ouargla', 'ar' => 'ورقلة']],
            ['id' => 31, 'country_id' => 1, 'name' => ['en' => 'Oran', 'ar' => 'وهران']],
            ['id' => 32, 'country_id' => 1, 'name' => ['en' => 'El Bayadh', 'ar' => 'البيض']],
            ['id' => 33, 'country_id' => 1, 'name' => ['en' => 'Illizi', 'ar' => 'إليزي']],
            ['id' => 34, 'country_id' => 1, 'name' => ['en' => 'Bordj Bou Arréridj', 'ar' => 'برج بوعريريج']],
            ['id' => 35, 'country_id' => 1, 'name' => ['en' => 'Boumerdès', 'ar' => 'بومرداس']],
            ['id' => 36, 'country_id' => 1, 'name' => ['en' => 'El Tarf', 'ar' => 'الطارف']],
            ['id' => 37, 'country_id' => 1, 'name' => ['en' => 'Tindouf', 'ar' => 'تندوف']],
            ['id' => 38, 'country_id' => 1, 'name' => ['en' => 'Tissemsilt', 'ar' => 'تيسمسيلت']],
            ['id' => 39, 'country_id' => 1, 'name' => ['en' => 'El Oued', 'ar' => 'الوادي']],
            ['id' => 40, 'country_id' => 1, 'name' => ['en' => 'Khenchela', 'ar' => 'خنشلة']],
            ['id' => 41, 'country_id' => 1, 'name' => ['en' => 'Souk Ahras', 'ar' => 'سوق أهراس']],
            ['id' => 42, 'country_id' => 1, 'name' => ['en' => 'Tipaza', 'ar' => 'تيبازة']],
            ['id' => 43, 'country_id' => 1, 'name' => ['en' => 'Mila', 'ar' => 'ميلة']],
            ['id' => 44, 'country_id' => 1, 'name' => ['en' => 'Aïn Defla', 'ar' => 'عين الدفلى']],
            ['id' => 45, 'country_id' => 1, 'name' => ['en' => 'Naâma', 'ar' => 'النعامة']],
            ['id' => 46, 'country_id' => 1, 'name' => ['en' => 'Aïn Témouchent', 'ar' => 'عين تموشنت']],
            ['id' => 47, 'country_id' => 1, 'name' => ['en' => 'Ghardaïa', 'ar' => 'غرداية']],
            ['id' => 48, 'country_id' => 1, 'name' => ['en' => 'Relizane', 'ar' => 'غليزان']],
            ['id' => 49, 'country_id' => 1, 'name' => ['en' => 'Timimoun', 'ar' => 'تيميمون']],
            ['id' => 50, 'country_id' => 1, 'name' => ['en' => 'Bordj Badji Mokhtar', 'ar' => 'برج باجي مختار']],
            ['id' => 51, 'country_id' => 1, 'name' => ['en' => 'Ouled Djellal', 'ar' => 'أولاد جلال']],
            ['id' => 52, 'country_id' => 1, 'name' => ['en' => 'Béni Abbès', 'ar' => 'بني عباس']],
            ['id' => 53, 'country_id' => 1, 'name' => ['en' => 'In Salah', 'ar' => 'عين صالح']],
            ['id' => 54, 'country_id' => 1, 'name' => ['en' => 'In Guezzam', 'ar' => 'عين قزام']],
            ['id' => 55, 'country_id' => 1, 'name' => ['en' => 'Touggourt', 'ar' => 'تقرت']],
            ['id' => 56, 'country_id' => 1, 'name' => ['en' => 'Djanet', 'ar' => 'جانت']],
            ['id' => 57, 'country_id' => 1, 'name' => ['en' => 'El M’Ghair', 'ar' => 'المغير']],
            ['id' => 58, 'country_id' => 1, 'name' => ['en' => 'El Meniaa', 'ar' => 'المنيعة']],

            // دولة البحرين
            ['id' => 59, 'country_id' => 2, 'name' => ['en' => 'Capital', 'ar' => 'العاصمة']],
            ['id' => 60, 'country_id' => 2, 'name' => ['en' => 'Muharraq', 'ar' => 'المحرق']],
            ['id' => 61, 'country_id' => 2, 'name' => ['en' => 'Northern', 'ar' => 'الشمالية']],
            ['id' => 62, 'country_id' => 2, 'name' => ['en' => 'Southern', 'ar' => 'الجنوبية']],

            // دولة جزر القمر
            ['id' => 63, 'country_id' => 3, 'name' => ['en' => 'Anjouan', 'ar' => 'أنجوان']],
            ['id' => 64, 'country_id' => 3, 'name' => ['en' => 'Grande Comore', 'ar' => 'القمر الكبرى']],
            ['id' => 65, 'country_id' => 3, 'name' => ['en' => 'Mohéli', 'ar' => 'موهيلي']],

            // دولة جيبوتي
            ['id' => 66, 'country_id' => 4, 'name' => ['en' => 'Ali Sabieh', 'ar' => 'علي صبيح']],
            ['id' => 67, 'country_id' => 4, 'name' => ['en' => 'Arta', 'ar' => 'أرتا']],
            ['id' => 68, 'country_id' => 4, 'name' => ['en' => 'Dikhil', 'ar' => 'دخيل']],
            ['id' => 69, 'country_id' => 4, 'name' => ['en' => 'Djibouti', 'ar' => 'جيبوتي']],
            ['id' => 70, 'country_id' => 4, 'name' => ['en' => 'Obock', 'ar' => 'أوبوك']],
            ['id' => 71, 'country_id' => 4, 'name' => ['en' => 'Tadjourah', 'ar' => 'تاجورة']],

            // دولة مصر
            ['id' => 72, 'country_id' => 5, 'name' => ['en' => 'Alexandria', 'ar' => 'الإسكندرية']],
            ['id' => 73, 'country_id' => 5, 'name' => ['en' => 'Aswan', 'ar' => 'أسوان']],
            ['id' => 74, 'country_id' => 5, 'name' => ['en' => 'Asyut', 'ar' => 'أسيوط']],
            ['id' => 75, 'country_id' => 5, 'name' => ['en' => 'Beheira', 'ar' => 'البحيرة']],
            ['id' => 76, 'country_id' => 5, 'name' => ['en' => 'Beni Suef', 'ar' => 'بني سويف']],
            ['id' => 77, 'country_id' => 5, 'name' => ['en' => 'Dakahlia', 'ar' => 'الدقهلية']],
            ['id' => 78, 'country_id' => 5, 'name' => ['en' => 'Damietta', 'ar' => 'دمياط']],
            ['id' => 79, 'country_id' => 5, 'name' => ['en' => 'Faiyum', 'ar' => 'الفيوم']],
            ['id' => 80, 'country_id' => 5, 'name' => ['en' => 'Gharbia', 'ar' => 'الغربية']],
            ['id' => 81, 'country_id' => 5, 'name' => ['en' => 'Giza', 'ar' => 'الجيزة']],
            ['id' => 82, 'country_id' => 5, 'name' => ['en' => 'Ismailia', 'ar' => 'الإسماعيلية']],
            ['id' => 83, 'country_id' => 5, 'name' => ['en' => 'Kafr El Sheikh', 'ar' => 'كفر الشيخ']],
            ['id' => 84, 'country_id' => 5, 'name' => ['en' => 'Luxor', 'ar' => 'الأقصر']],
            ['id' => 85, 'country_id' => 5, 'name' => ['en' => 'Matruh', 'ar' => 'مطروح']],
            ['id' => 86, 'country_id' => 5, 'name' => ['en' => 'Minya', 'ar' => 'المنيا']],
            ['id' => 87, 'country_id' => 5, 'name' => ['en' => 'Monufia', 'ar' => 'المنوفية']],
            ['id' => 88, 'country_id' => 5, 'name' => ['en' => 'New Valley', 'ar' => 'الوادي الجديد']],
            ['id' => 89, 'country_id' => 5, 'name' => ['en' => 'North Sinai', 'ar' => 'شمال سيناء']],
            ['id' => 90, 'country_id' => 5, 'name' => ['en' => 'Port Said', 'ar' => 'بورسعيد']],
            ['id' => 91, 'country_id' => 5, 'name' => ['en' => 'Qalyubia', 'ar' => 'القليوبية']],
            ['id' => 92, 'country_id' => 5, 'name' => ['en' => 'Qena', 'ar' => 'قنا']],
            ['id' => 93, 'country_id' => 5, 'name' => ['en' => 'Red Sea', 'ar' => 'البحر الأحمر']],
            ['id' => 94, 'country_id' => 5, 'name' => ['en' => 'Sharqia', 'ar' => 'الشرقية']],
            ['id' => 95, 'country_id' => 5, 'name' => ['en' => 'Sohag', 'ar' => 'سوهاج']],
            ['id' => 96, 'country_id' => 5, 'name' => ['en' => 'South Sinai', 'ar' => 'جنوب سيناء']],
            ['id' => 97, 'country_id' => 5, 'name' => ['en' => 'Suez', 'ar' => 'السويس']],

            // دولة العراق
            ['id' => 98, 'country_id' => 6, 'name' => ['en' => 'Al Anbar', 'ar' => 'الأنبار']],
            ['id' => 99, 'country_id' => 6, 'name' => ['en' => 'Babil', 'ar' => 'بابل']],
            ['id' => 100, 'country_id' => 6, 'name' => ['en' => 'Baghdad', 'ar' => 'بغداد']],
            ['id' => 101, 'country_id' => 6, 'name' => ['en' => 'Basra', 'ar' => 'البصرة']],
            ['id' => 102, 'country_id' => 6, 'name' => ['en' => 'Dhi Qar', 'ar' => 'ذي قار']],
            ['id' => 103, 'country_id' => 6, 'name' => ['en' => 'Al-Qādisiyyah', 'ar' => 'القادسية']],
            ['id' => 104, 'country_id' => 6, 'name' => ['en' => 'Diyala', 'ar' => 'ديالى']],
            ['id' => 105, 'country_id' => 6, 'name' => ['en' => 'Dohuk', 'ar' => 'دهوك']],
            ['id' => 106, 'country_id' => 6, 'name' => ['en' => 'Erbil', 'ar' => 'أربيل']],
            ['id' => 107, 'country_id' => 6, 'name' => ['en' => 'Karbala', 'ar' => 'كربلاء']],
            ['id' => 108, 'country_id' => 6, 'name' => ['en' => 'Kirkuk', 'ar' => 'كركوك']],
            ['id' => 109, 'country_id' => 6, 'name' => ['en' => 'Maysan', 'ar' => 'ميسان']],
            ['id' => 110, 'country_id' => 6, 'name' => ['en' => 'Muthanna', 'ar' => 'المثنى']],
            ['id' => 111, 'country_id' => 6, 'name' => ['en' => 'Najaf', 'ar' => 'النجف']],
            ['id' => 112, 'country_id' => 6, 'name' => ['en' => 'Nineveh', 'ar' => 'نينوى']],
            ['id' => 113, 'country_id' => 6, 'name' => ['en' => 'Saladin', 'ar' => 'صلاح الدين']],
            ['id' => 114, 'country_id' => 6, 'name' => ['en' => 'Sulaymaniyah', 'ar' => 'السليمانية']],
            ['id' => 115, 'country_id' => 6, 'name' => ['en' => 'Wasit', 'ar' => 'واسط']],

            // دولة الأردن
            ['id' => 116, 'country_id' => 7, 'name' => ['en' => 'Ajloun', 'ar' => 'عجلون']],
            ['id' => 117, 'country_id' => 7, 'name' => ['en' => 'Amman', 'ar' => 'عمان']],
            ['id' => 118, 'country_id' => 7, 'name' => ['en' => 'Aqaba', 'ar' => 'العقبة']],
            ['id' => 119, 'country_id' => 7, 'name' => ['en' => 'Balqa', 'ar' => 'البلقاء']],
            ['id' => 120, 'country_id' => 7, 'name' => ['en' => 'Irbid', 'ar' => 'إربد']],
            ['id' => 121, 'country_id' => 7, 'name' => ['en' => 'Jerash', 'ar' => 'جرش']],
            ['id' => 122, 'country_id' => 7, 'name' => ['en' => 'Karak', 'ar' => 'الكرك']],
            ['id' => 123, 'country_id' => 7, 'name' => ['en' => 'Ma\'an', 'ar' => 'معان']],
            ['id' => 124, 'country_id' => 7, 'name' => ['en' => 'Madaba', 'ar' => 'مادبا']],
            ['id' => 125, 'country_id' => 7, 'name' => ['en' => 'Mafraq', 'ar' => 'المفرق']],
            ['id' => 126, 'country_id' => 7, 'name' => ['en' => 'Tafilah', 'ar' => 'الطفيلة']],
            ['id' => 127, 'country_id' => 7, 'name' => ['en' => 'Zarqa', 'ar' => 'الزرقاء']],

            // دولة الكويت
            ['id' => 128, 'country_id' => 8, 'name' => ['en' => 'Al Ahmadi', 'ar' => 'الأحمدي']],
            ['id' => 129, 'country_id' => 8, 'name' => ['en' => 'Al Asimah', 'ar' => 'العاصمة']],
            ['id' => 130, 'country_id' => 8, 'name' => ['en' => 'Al Farwaniyah', 'ar' => 'الفروانية']],
            ['id' => 131, 'country_id' => 8, 'name' => ['en' => 'Al Jahra', 'ar' => 'الجهراء']],
            ['id' => 132, 'country_id' => 8, 'name' => ['en' => 'Hawalli', 'ar' => 'حولي']],
            ['id' => 133, 'country_id' => 8, 'name' => ['en' => 'Mubarak Al-Kabeer', 'ar' => 'مبارك الكبير']],

            // دولة لبنان
            ['id' => 134, 'country_id' => 9, 'name' => ['en' => 'Akkar', 'ar' => 'عكار']],
            ['id' => 135, 'country_id' => 9, 'name' => ['en' => 'Baalbek-Hermel', 'ar' => 'بعلبك-الهرمل']],
            ['id' => 136, 'country_id' => 9, 'name' => ['en' => 'Beirut', 'ar' => 'بيروت']],
            ['id' => 137, 'country_id' => 9, 'name' => ['en' => 'Beqaa', 'ar' => 'البقاع']],
            ['id' => 138, 'country_id' => 9, 'name' => ['en' => 'Mount Lebanon', 'ar' => 'جبل لبنان']],
            ['id' => 139, 'country_id' => 9, 'name' => ['en' => 'Nabatieh', 'ar' => 'النبطية']],
            ['id' => 140, 'country_id' => 9, 'name' => ['en' => 'North', 'ar' => 'الشمال']],
            ['id' => 141, 'country_id' => 9, 'name' => ['en' => 'South', 'ar' => 'الجنوب']],

            // دولة ليبيا
            ['id' => 142, 'country_id' => 10, 'name' => ['en' => 'Al Butnan', 'ar' => 'البطنان']],
            ['id' => 143, 'country_id' => 10, 'name' => ['en' => 'Al Jabal al Akhdar', 'ar' => 'الجبل الأخضر']],
            ['id' => 144, 'country_id' => 10, 'name' => ['en' => 'Al Jabal al Gharbi', 'ar' => 'الجبل الغربي']],
            ['id' => 145, 'country_id' => 10, 'name' => ['en' => 'Al Jufrah', 'ar' => 'الجفرة']],
            ['id' => 146, 'country_id' => 10, 'name' => ['en' => 'Al Kufrah', 'ar' => 'الكفرة']],
            ['id' => 147, 'country_id' => 10, 'name' => ['en' => 'Al Marj', 'ar' => 'المرج']],
            ['id' => 148, 'country_id' => 10, 'name' => ['en' => 'Al Wahat', 'ar' => 'الواحات']],
            ['id' => 149, 'country_id' => 10, 'name' => ['en' => 'Benghazi', 'ar' => 'بنغازي']],
            ['id' => 150, 'country_id' => 10, 'name' => ['en' => 'Derna', 'ar' => 'درنة']],
            ['id' => 151, 'country_id' => 10, 'name' => ['en' => 'Ghat', 'ar' => 'غات']],
            ['id' => 152, 'country_id' => 10, 'name' => ['en' => 'Misrata', 'ar' => 'مصراتة']],
            ['id' => 153, 'country_id' => 10, 'name' => ['en' => 'Murzuq', 'ar' => 'مرزق']],
            ['id' => 154, 'country_id' => 10, 'name' => ['en' => 'Nalut', 'ar' => 'نالوت']],
            ['id' => 155, 'country_id' => 10, 'name' => ['en' => 'Sabha', 'ar' => 'سبها']],
            ['id' => 156, 'country_id' => 10, 'name' => ['en' => 'Sirte', 'ar' => 'سرت']],
            ['id' => 157, 'country_id' => 10, 'name' => ['en' => 'Tripoli', 'ar' => 'طرابلس']],
            ['id' => 158, 'country_id' => 10, 'name' => ['en' => 'Wadi al Hayaa', 'ar' => 'وادي الحياة']],
            ['id' => 159, 'country_id' => 10, 'name' => ['en' => 'Wadi ash Shatiʼ', 'ar' => 'وادي الشاطئ']],
            ['id' => 160, 'country_id' => 10, 'name' => ['en' => 'Zawiya', 'ar' => 'الزاوية']],

            // دولة موريتانيا
            ['id' => 161, 'country_id' => 11, 'name' => ['en' => 'Adrar', 'ar' => 'أدرار']],
            ['id' => 162, 'country_id' => 11, 'name' => ['en' => 'Assaba', 'ar' => 'العصابة']],
            ['id' => 163, 'country_id' => 11, 'name' => ['en' => 'Brakna', 'ar' => 'براكنة']],
            ['id' => 164, 'country_id' => 11, 'name' => ['en' => 'Dakhlet Nouadhibou', 'ar' => 'داخلت نواذيبو']],
            ['id' => 165, 'country_id' => 11, 'name' => ['en' => 'Gorgol', 'ar' => 'كوركول']],
            ['id' => 166, 'country_id' => 11, 'name' => ['en' => 'Guidimaka', 'ar' => 'كيدي ماغا']],
            ['id' => 167, 'country_id' => 11, 'name' => ['en' => 'Hodh Ech Chargui', 'ar' => 'الحوض الشرقي']],
            ['id' => 168, 'country_id' => 11, 'name' => ['en' => 'Hodh El Gharbi', 'ar' => 'الحوض الغربي']],
            ['id' => 169, 'country_id' => 11, 'name' => ['en' => 'Inchiri', 'ar' => 'إنشيري']],
            ['id' => 170, 'country_id' => 11, 'name' => ['en' => 'Nouakchott Nord', 'ar' => 'نواكشوط الشمالية']],
            ['id' => 171, 'country_id' => 11, 'name' => ['en' => 'Nouakchott Ouest', 'ar' => 'نواكشوط الغربية']],
            ['id' => 172, 'country_id' => 11, 'name' => ['en' => 'Nouakchott Sud', 'ar' => 'نواكشوط الجنوبية']],
            ['id' => 173, 'country_id' => 11, 'name' => ['en' => 'Tagant', 'ar' => 'تكانت']],
            ['id' => 174, 'country_id' => 11, 'name' => ['en' => 'Tiris Zemmour', 'ar' => 'تيرس زمور']],
            ['id' => 175, 'country_id' => 11, 'name' => ['en' => 'Trarza', 'ar' => 'ترارزة']],

            // دولة المغرب
            ['id' => 176, 'country_id' => 12, 'name' => ['en' => 'Béni Mellal-Khénifra', 'ar' => 'بني ملال-خنيفرة']],
            ['id' => 177, 'country_id' => 12, 'name' => ['en' => 'Casablanca-Settat', 'ar' => 'الدار البيضاء-سطات']],
            ['id' => 178, 'country_id' => 12, 'name' => ['en' => 'Drâa-Tafilalet', 'ar' => 'درعة-تافيلالت']],
            ['id' => 179, 'country_id' => 12, 'name' => ['en' => 'Dakhla-Oued Ed-Dahab', 'ar' => 'الداخلة-وادي الذهب']],
            ['id' => 180, 'country_id' => 12, 'name' => ['en' => 'Fès-Meknès', 'ar' => 'فاس-مكناس']],
            ['id' => 181, 'country_id' => 12, 'name' => ['en' => 'Guelmim-Oued Noun', 'ar' => 'كلميم-وادي نون']],
            ['id' => 182, 'country_id' => 12, 'name' => ['en' => 'Laâyoune-Sakia El Hamra', 'ar' => 'العيون-الساقية الحمراء']],
            ['id' => 183, 'country_id' => 12, 'name' => ['en' => 'Marrakech-Safi', 'ar' => 'مراكش-آسفي']],
            ['id' => 184, 'country_id' => 12, 'name' => ['en' => 'Oriental', 'ar' => 'الشرق']],
            ['id' => 185, 'country_id' => 12, 'name' => ['en' => 'Rabat-Salé-Kénitra', 'ar' => 'الرباط-سلا-القنيطرة']],
            ['id' => 186, 'country_id' => 12, 'name' => ['en' => 'Souss-Massa', 'ar' => 'سوس-ماسة']],
            ['id' => 187, 'country_id' => 12, 'name' => ['en' => 'Tanger-Tétouan-Al Hoceïma', 'ar' => 'طنجة-تطوان-الحسيمة']],

            // دولة عمان
            ['id' => 188, 'country_id' => 13, 'name' => ['en' => 'Ad Dakhiliyah', 'ar' => 'الداخلية']],
            ['id' => 189, 'country_id' => 13, 'name' => ['en' => 'Ad Dhahirah', 'ar' => 'الظاهرة']],
            ['id' => 190, 'country_id' => 13, 'name' => ['en' => 'Al Batinah North', 'ar' => 'شمال الباطنة']],
            ['id' => 191, 'country_id' => 13, 'name' => ['en' => 'Al Batinah South', 'ar' => 'جنوب الباطنة']],
            ['id' => 192, 'country_id' => 13, 'name' => ['en' => 'Al Buraimi', 'ar' => 'البريمي']],
            ['id' => 193, 'country_id' => 13, 'name' => ['en' => 'Al Wusta', 'ar' => 'الوسطى']],
            ['id' => 194, 'country_id' => 13, 'name' => ['en' => 'Dhofar', 'ar' => 'ظفار']],
            ['id' => 195, 'country_id' => 13, 'name' => ['en' => 'Musandam', 'ar' => 'مسندم']],
            ['id' => 196, 'country_id' => 13, 'name' => ['en' => 'Muscat', 'ar' => 'مسقط']],
            ['id' => 197, 'country_id' => 13, 'name' => ['en' => 'Ash Sharqiyah North', 'ar' => 'شمال الشرقية']],
            ['id' => 198, 'country_id' => 13, 'name' => ['en' => 'Ash Sharqiyah South', 'ar' => 'جنوب الشرقية']],

            // دولة فلسطين
            ['id' => 199, 'country_id' => 14, 'name' => ['en' => 'Bethlehem', 'ar' => 'بيت لحم']],
            ['id' => 200, 'country_id' => 14, 'name' => ['en' => 'Deir al-Balah', 'ar' => 'دير البلح']],
            ['id' => 201, 'country_id' => 14, 'name' => ['en' => 'Gaza', 'ar' => 'غزة']],
            ['id' => 202, 'country_id' => 14, 'name' => ['en' => 'Hebron', 'ar' => 'الخليل']],
            ['id' => 203, 'country_id' => 14, 'name' => ['en' => 'Jenin', 'ar' => 'جنين']],
            ['id' => 204, 'country_id' => 14, 'name' => ['en' => 'Jericho', 'ar' => 'أريحا']],
            ['id' => 205, 'country_id' => 14, 'name' => ['en' => 'Jerusalem', 'ar' => 'القدس']],
            ['id' => 206, 'country_id' => 14, 'name' => ['en' => 'Khan Yunis', 'ar' => 'خان يونس']],
            ['id' => 207, 'country_id' => 14, 'name' => ['en' => 'Nablus', 'ar' => 'نابلس']],
            ['id' => 208, 'country_id' => 14, 'name' => ['en' => 'North Gaza', 'ar' => 'شمال غزة']],
            ['id' => 209, 'country_id' => 14, 'name' => ['en' => 'Qalqilya', 'ar' => 'قلقيلية']],
            ['id' => 210, 'country_id' => 14, 'name' => ['en' => 'Rafah', 'ar' => 'رفح']],
            ['id' => 211, 'country_id' => 14, 'name' => ['en' => 'Ramallah and al-Bireh', 'ar' => 'رام الله والبيرة']],
            ['id' => 212, 'country_id' => 14, 'name' => ['en' => 'Salfit', 'ar' => 'سلفيت']],
            ['id' => 213, 'country_id' => 14, 'name' => ['en' => 'Tubas', 'ar' => 'طوباس']],
            ['id' => 214, 'country_id' => 14, 'name' => ['en' => 'Tulkarm', 'ar' => 'طولكرم']],

            // دولة قطر
            ['id' => 215, 'country_id' => 15, 'name' => ['en' => 'Ad Dawhah', 'ar' => 'الدوحة']],
            ['id' => 216, 'country_id' => 15, 'name' => ['en' => 'Al Khor', 'ar' => 'الخور']],
            ['id' => 217, 'country_id' => 15, 'name' => ['en' => 'Al Rayyan', 'ar' => 'الريان']],
            ['id' => 218, 'country_id' => 15, 'name' => ['en' => 'Al Shamal', 'ar' => 'الشمال']],
            ['id' => 219, 'country_id' => 15, 'name' => ['en' => 'Al Wakrah', 'ar' => 'الوكرة']],
            ['id' => 220, 'country_id' => 15, 'name' => ['en' => 'Al-Shahaniya', 'ar' => 'الشحانية']],
            ['id' => 221, 'country_id' => 15, 'name' => ['en' => 'Umm Salal', 'ar' => 'أم صلال']],
            ['id' => 222, 'country_id' => 15, 'name' => ['en' => 'Dukhan', 'ar' => 'دخان']],

            // دولة السعودية
            ['id' => 223, 'country_id' => 16, 'name' => ['en' => 'Al Bahah', 'ar' => 'الباحة']],
            ['id' => 224, 'country_id' => 16, 'name' => ['en' => 'Al Jawf', 'ar' => 'الجوف']],
            ['id' => 225, 'country_id' => 16, 'name' => ['en' => 'Al Madinah', 'ar' => 'المدينة المنورة']],
            ['id' => 226, 'country_id' => 16, 'name' => ['en' => 'Al Qassim', 'ar' => 'القصيم']],
            ['id' => 227, 'country_id' => 16, 'name' => ['en' => 'Asir', 'ar' => 'عسير']],
            ['id' => 228, 'country_id' => 16, 'name' => ['en' => 'Eastern Province', 'ar' => 'الشرقية']],
            ['id' => 229, 'country_id' => 16, 'name' => ['en' => 'Ha\'il', 'ar' => 'حائل']],
            ['id' => 230, 'country_id' => 16, 'name' => ['en' => 'Jazan', 'ar' => 'جازان']],
            ['id' => 231, 'country_id' => 16, 'name' => ['en' => 'Makkah', 'ar' => 'مكة المكرمة']],
            ['id' => 232, 'country_id' => 16, 'name' => ['en' => 'Najran', 'ar' => 'نجران']],
            ['id' => 233, 'country_id' => 16, 'name' => ['en' => 'Northern Borders', 'ar' => 'الحدود الشمالية']],
            ['id' => 234, 'country_id' => 16, 'name' => ['en' => 'Riyadh', 'ar' => 'الرياض']],
            ['id' => 235, 'country_id' => 16, 'name' => ['en' => 'Tabuk', 'ar' => 'تبوك']],

            // دولة الصومال
            ['id' => 236, 'country_id' => 17, 'name' => ['en' => 'Awdal', 'ar' => 'أودال']],
            ['id' => 237, 'country_id' => 17, 'name' => ['en' => 'Bakool', 'ar' => 'باكول']],
            ['id' => 238, 'country_id' => 17, 'name' => ['en' => 'Banaadir', 'ar' => 'بنادر']],
            ['id' => 239, 'country_id' => 17, 'name' => ['en' => 'Bari', 'ar' => 'باري']],
            ['id' => 240, 'country_id' => 17, 'name' => ['en' => 'Bay', 'ar' => 'باي']],
            ['id' => 241, 'country_id' => 17, 'name' => ['en' => 'Galguduud', 'ar' => 'جلجدود']],
            ['id' => 242, 'country_id' => 17, 'name' => ['en' => 'Gedo', 'ar' => 'جدو']],
            ['id' => 243, 'country_id' => 17, 'name' => ['en' => 'Hiiraan', 'ar' => 'هيران']],
            ['id' => 244, 'country_id' => 17, 'name' => ['en' => 'Lower Juba', 'ar' => 'جوبا السفلى']],
            ['id' => 245, 'country_id' => 17, 'name' => ['en' => 'Lower Shabelle', 'ar' => 'شبيلي السفلى']],
            ['id' => 246, 'country_id' => 17, 'name' => ['en' => 'Middle Juba', 'ar' => 'جوبا الوسطى']],
            ['id' => 247, 'country_id' => 17, 'name' => ['en' => 'Middle Shabelle', 'ar' => 'شبيلي الوسطى']],
            ['id' => 248, 'country_id' => 17, 'name' => ['en' => 'Mudug', 'ar' => 'مدج']],
            ['id' => 249, 'country_id' => 17, 'name' => ['en' => 'Nugaal', 'ar' => 'نوجال']],
            ['id' => 250, 'country_id' => 17, 'name' => ['en' => 'Sanaag', 'ar' => 'سناج']],
            ['id' => 251, 'country_id' => 17, 'name' => ['en' => 'Sool', 'ar' => 'سول']],
            ['id' => 252, 'country_id' => 17, 'name' => ['en' => 'Togdheer', 'ar' => 'توغدير']],
            ['id' => 253, 'country_id' => 17, 'name' => ['en' => 'Woqooyi Galbeed', 'ar' => 'وقويي جالبيد']],

            // دولة السودان
            ['id' => 254, 'country_id' => 18, 'name' => ['en' => 'Al Jazirah', 'ar' => 'الجزيرة']],
            ['id' => 255, 'country_id' => 18, 'name' => ['en' => 'Al Qadarif', 'ar' => 'القضارف']],
            ['id' => 256, 'country_id' => 18, 'name' => ['en' => 'Blue Nile', 'ar' => 'النيل الأزرق']],
            ['id' => 257, 'country_id' => 18, 'name' => ['en' => 'Central Darfur', 'ar' => 'وسط دارفور']],
            ['id' => 258, 'country_id' => 18, 'name' => ['en' => 'East Darfur', 'ar' => 'شرق دارفور']],
            ['id' => 259, 'country_id' => 18, 'name' => ['en' => 'Kassala', 'ar' => 'كسلا']],
            ['id' => 260, 'country_id' => 18, 'name' => ['en' => 'Khartoum', 'ar' => 'الخرطوم']],
            ['id' => 261, 'country_id' => 18, 'name' => ['en' => 'North Darfur', 'ar' => 'شمال دارفور']],
            ['id' => 262, 'country_id' => 18, 'name' => ['en' => 'North Kordofan', 'ar' => 'شمال كردفان']],
            ['id' => 263, 'country_id' => 18, 'name' => ['en' => 'Northern', 'ar' => 'الشمالية']],
            ['id' => 264, 'country_id' => 18, 'name' => ['en' => 'Red Sea', 'ar' => 'البحر الأحمر']],
            ['id' => 265, 'country_id' => 18, 'name' => ['en' => 'River Nile', 'ar' => 'نهر النيل']],
            ['id' => 266, 'country_id' => 18, 'name' => ['en' => 'Sennar', 'ar' => 'سنار']],
            ['id' => 267, 'country_id' => 18, 'name' => ['en' => 'South Darfur', 'ar' => 'جنوب دارفور']],
            ['id' => 268, 'country_id' => 18, 'name' => ['en' => 'South Kordofan', 'ar' => 'جنوب كردفان']],
            ['id' => 269, 'country_id' => 18, 'name' => ['en' => 'West Darfur', 'ar' => 'غرب دارفور']],
            ['id' => 270, 'country_id' => 18, 'name' => ['en' => 'West Kordofan', 'ar' => 'غرب كردفان']],
            ['id' => 271, 'country_id' => 18, 'name' => ['en' => 'White Nile', 'ar' => 'النيل الأبيض']],

            // دولة سوريا
            ['id' => 272, 'country_id' => 19, 'name' => ['en' => 'Aleppo', 'ar' => 'حلب']],
            ['id' => 273, 'country_id' => 19, 'name' => ['en' => 'Al-Hasakah', 'ar' => 'الحسكة']],
            ['id' => 274, 'country_id' => 19, 'name' => ['en' => 'Al-Raqqah', 'ar' => 'الرقة']],
            ['id' => 275, 'country_id' => 19, 'name' => ['en' => 'As-Suwayda', 'ar' => 'السويداء']],
            ['id' => 276, 'country_id' => 19, 'name' => ['en' => 'Damascus', 'ar' => 'دمشق']],
            ['id' => 277, 'country_id' => 19, 'name' => ['en' => 'Daraa', 'ar' => 'درعا']],
            ['id' => 278, 'country_id' => 19, 'name' => ['en' => 'Deir ez-Zor', 'ar' => 'دير الزور']],
            ['id' => 279, 'country_id' => 19, 'name' => ['en' => 'Hama', 'ar' => 'حماة']],
            ['id' => 280, 'country_id' => 19, 'name' => ['en' => 'Homs', 'ar' => 'حمص']],
            ['id' => 281, 'country_id' => 19, 'name' => ['en' => 'Idlib', 'ar' => 'إدلب']],
            ['id' => 282, 'country_id' => 19, 'name' => ['en' => 'Latakia', 'ar' => 'اللاذقية']],
            ['id' => 283, 'country_id' => 19, 'name' => ['en' => 'Quneitra', 'ar' => 'القنيطرة']],
            ['id' => 284, 'country_id' => 19, 'name' => ['en' => 'Rif Dimashq', 'ar' => 'ريف دمشق']],
            ['id' => 285, 'country_id' => 19, 'name' => ['en' => 'Tartus', 'ar' => 'طرطوس']],

            // دولة تونس
            ['id' => 286, 'country_id' => 20, 'name' => ['en' => 'Ariana', 'ar' => 'أريانة']],
            ['id' => 287, 'country_id' => 20, 'name' => ['en' => 'Béja', 'ar' => 'باجة']],
            ['id' => 288, 'country_id' => 20, 'name' => ['en' => 'Ben Arous', 'ar' => 'بن عروس']],
            ['id' => 289, 'country_id' => 20, 'name' => ['en' => 'Bizerte', 'ar' => 'بنزرت']],
            ['id' => 290, 'country_id' => 20, 'name' => ['en' => 'Gabès', 'ar' => 'قابس']],
            ['id' => 291, 'country_id' => 20, 'name' => ['en' => 'Gafsa', 'ar' => 'قفصة']],
            ['id' => 292, 'country_id' => 20, 'name' => ['en' => 'Jendouba', 'ar' => 'جندوبة']],
            ['id' => 293, 'country_id' => 20, 'name' => ['en' => 'Kairouan', 'ar' => 'القيروان']],
            ['id' => 294, 'country_id' => 20, 'name' => ['en' => 'Kasserine', 'ar' => 'القصرين']],
            ['id' => 295, 'country_id' => 20, 'name' => ['en' => 'Kébili', 'ar' => 'قبلي']],
            ['id' => 296, 'country_id' => 20, 'name' => ['en' => 'Kef', 'ar' => 'الكاف']],
            ['id' => 297, 'country_id' => 20, 'name' => ['en' => 'Mahdia', 'ar' => 'المهدية']],
            ['id' => 298, 'country_id' => 20, 'name' => ['en' => 'Manouba', 'ar' => 'منوبة']],
            ['id' => 299, 'country_id' => 20, 'name' => ['en' => 'Médenine', 'ar' => 'مدنين']],
            ['id' => 300, 'country_id' => 20, 'name' => ['en' => 'Monastir', 'ar' => 'المنستير']],
            ['id' => 301, 'country_id' => 20, 'name' => ['en' => 'Nabeul', 'ar' => 'نابل']],
            ['id' => 302, 'country_id' => 20, 'name' => ['en' => 'Sfax', 'ar' => 'صفاقس']],
            ['id' => 303, 'country_id' => 20, 'name' => ['en' => 'Sidi Bouzid', 'ar' => 'سيدي بوزيد']],
            ['id' => 304, 'country_id' => 20, 'name' => ['en' => 'Siliana', 'ar' => 'سليانة']],
            ['id' => 305, 'country_id' => 20, 'name' => ['en' => 'Sousse', 'ar' => 'سوسة']],
            ['id' => 306, 'country_id' => 20, 'name' => ['en' => 'Tataouine', 'ar' => 'تطاوين']],
            ['id' => 307, 'country_id' => 20, 'name' => ['en' => 'Tozeur', 'ar' => 'توزر']],
            ['id' => 308, 'country_id' => 20, 'name' => ['en' => 'Tunis', 'ar' => 'تونس']],
            ['id' => 309, 'country_id' => 20, 'name' => ['en' => 'Zaghouan', 'ar' => 'زغوان']],

            // دولة الإمارات
            ['id' => 310, 'country_id' => 21, 'name' => ['en' => 'Abu Dhabi', 'ar' => 'أبوظبي']],
            ['id' => 311, 'country_id' => 21, 'name' => ['en' => 'Ajman', 'ar' => 'عجمان']],
            ['id' => 312, 'country_id' => 21, 'name' => ['en' => 'Dubai', 'ar' => 'دبي']],
            ['id' => 313, 'country_id' => 21, 'name' => ['en' => 'Fujairah', 'ar' => 'الفجيرة']],
            ['id' => 314, 'country_id' => 21, 'name' => ['en' => 'Ras al-Khaimah', 'ar' => 'رأس الخيمة']],
            ['id' => 315, 'country_id' => 21, 'name' => ['en' => 'Sharjah', 'ar' => 'الشارقة']],
            ['id' => 316, 'country_id' => 21, 'name' => ['en' => 'Umm al-Quwain', 'ar' => 'أم القيوين']],

            // دولة اليمن
            ['id' => 317, 'country_id' => 22, 'name' => ['en' => 'Abyan', 'ar' => 'أبين']],
            ['id' => 318, 'country_id' => 22, 'name' => ['en' => 'Aden', 'ar' => 'عدن']],
            ['id' => 319, 'country_id' => 22, 'name' => ['en' => 'Al Bayda', 'ar' => 'البيضاء']],
            ['id' => 320, 'country_id' => 22, 'name' => ['en' => 'Al Hudaydah', 'ar' => 'الحديدة']],
            ['id' => 321, 'country_id' => 22, 'name' => ['en' => 'Al Jawf', 'ar' => 'الجوف']],
            ['id' => 322, 'country_id' => 22, 'name' => ['en' => 'Al Mahrah', 'ar' => 'المحرة']],
            ['id' => 323, 'country_id' => 22, 'name' => ['en' => 'Al Mahwit', 'ar' => 'المحويت']],
            ['id' => 324, 'country_id' => 22, 'name' => ['en' => 'Amran', 'ar' => 'عمران']],
            ['id' => 325, 'country_id' => 22, 'name' => ['en' => 'Dhamar', 'ar' => 'ذمار']],
            ['id' => 326, 'country_id' => 22, 'name' => ['en' => 'Hadramaut', 'ar' => 'حضرموت']],
            ['id' => 327, 'country_id' => 22, 'name' => ['en' => 'Hajjah', 'ar' => 'حجة']],
            ['id' => 328, 'country_id' => 22, 'name' => ['en' => 'Ibb', 'ar' => 'إب']],
            ['id' => 329, 'country_id' => 22, 'name' => ['en' => 'Lahij', 'ar' => 'لحج']],
            ['id' => 330, 'country_id' => 22, 'name' => ['en' => 'Ma\'rib', 'ar' => 'مأرب']],
            ['id' => 331, 'country_id' => 22, 'name' => ['en' => 'Sa\'dah', 'ar' => 'صعدة']],
            ['id' => 332, 'country_id' => 22, 'name' => ['en' => 'Sana\'a', 'ar' => 'صنعاء']],
            ['id' => 333, 'country_id' => 22, 'name' => ['en' => 'Shabwah', 'ar' => 'شبوة']],
            ['id' => 334, 'country_id' => 22, 'name' => ['en' => 'Socotra', 'ar' => 'سقطرى']],
            ['id' => 335, 'country_id' => 22, 'name' => ['en' => 'Ta\'izz', 'ar' => 'تعز']],
        ];

        foreach ($governments as $government) {
            Government::updateOrCreate(
                ['id' => $government['id']],
                [
                    'country_id' => $government['country_id'],
                    'name' => $government['name'] ,
                ]
            );
            GovernmentShippingPrice::updateOrCreate(['government_id' => $government['id']],['shipping_price' => 99.00]) ;
        }
    }
}
